[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
board_build.f_cpu = 80000000L
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    adafruit/Adafruit AHTX0@^2.0.0

build_flags =
    -DUSER_SETUP_LOADED
    -DUSE_HSPI_PORT
    -DILI9341_DRIVER
    -DLOAD_GLCD
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTFT_BACKLIGHT_ON=HIGH
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000